---
.pdkignore:
  paths:
    - /.*.yml
    - /pdk.yaml
    - /.pmtignore
    - /.git*
    - /.editorconfig
    - /provision.yaml

.rubocop.yml:
  default_configs:
    AllCops:
      NewCops: enable
    RSpec/RepeatedDescription:
      Exclude:
        - spec/classes/**.*.rb

Gemfile:
  required:
    ':development':
      - gem: hocon
        version: '~> 1.1'

spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
